---
kind: Service
apiVersion: v1
metadata:
  name: platform-take-home
  namespace: default 
  labels:
    app: platform-take-home
spec:
  type: LoadBalancer
  selector:
    app: platform-take-home 
  ports:
  - name: grpc-server 
    protocol: TCP
    port: 9008 
    targetPort: 9008
  - name: grpc-gw 
    protocol: TCP
    port: 8080 
    targetPort: 8080
  - name: metrics
    protocol: TCP
    port: 8081
    targetPort: 8081
